Repository TBD54566975/developer.tbd.website, pull requests merged in 2023-10, with the labels that each got.

#758 Add padding to the feedback widget #748 --> Fixed
  site/src/components/Card.jsx
  site/src/components/FeedbackWidget.jsx
  site/src/contributors.json
  site/src/util/code-snippets-map.json
Labels: hacktoberfest-accepted

#775 fix: Each Child in a list should have a unique "key" prop
  site/src/components/ApiDetails.jsx
Labels: hacktoberfest-accepted

#763 Example snippet to query by protocolPath and structure
  site/__tests__/web5/build/decentralized-web-nodes/query-from-dwn.test.js
  site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
  site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
Labels: documentation

#780 Highlight line in query-from-dwn.js
  site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
Labels: hacktoberfest-accepted

#750 Solved issue #745
  site/docs/web5/_quickstart-03-create-did.mdx
  site/docs/web5/_quickstart-05-write-record.mdx
  site/docs/web5/_quickstart-06-read-record.mdx
  site/docs/web5/_quickstart-07-update-record.mdx
  site/docs/web5/_quickstart-08-delete-record.mdx
Labels: hacktoberfest-accepted

#790 Typo readme
  README.md
Labels: hacktoberfest-accepted

#788 typo fixed in sync.md
  site/docs/web5/learn/sync.md
Labels: hacktoberfest-accepted

#789 added svg for twitter X logo
  site/static/img/twitter-icon.svg
Labels: hacktoberfest-accepted

#803 Fix typographical error in the Open Source Incubation Program page
  site/src/content/open-source/incubation/content.mdx
Labels: hacktoberfest-accepted

#814 Updated DOM property frameborder on blog page
  site/blog/2022-07-01-what-is-web5.md
  site/blog/2022-12-20-currency-of-freedom.md
  site/blog/2023-06-23-did-hack.md
Labels: hacktoberfest-accepted

#822 [DOCS] fixed typo in blogs
  site/blog/2023-06-23-did-hack.md
  site/blog/2023-08-11-who-really-owns-your-social-media-handles.md
Labels: hacktoberfest-accepted

#850 Moved Shopping Cart to Last Position
  site/src/theme/Footer.js
Labels: hacktoberfest-accepted

#852 removed full stop from box components
  site/src/content/projects/tbdex-protocol.mdx
  site/src/content/projects/web5/web5.js
Labels: hacktoberfest-accepted

#854 Added the missing full-stop
  site/docs/api.mdx
Labels: invalid

#857 Remove full-stops from all method descriptions
  site/api/web5-js/dwn/record.mdx
  site/api/web5-js/dwn/records.mdx
Labels: hacktoberfest-accepted

#859 Fixed the typo in Verifiable Presentations
  site/docs/ssi/verifiable-presentations.md
Labels: hacktoberfest

#836 Scroll restoration for button links
  site/src/components/Button.jsx
Labels: hacktoberfest-accepted

#874 Updated the 'Video' explore card link with youtube channel
  site/docs/docs-index.js
Labels: hacktoberfest-accepted

#871 Fixed Import CDN statements.
  site/api/web5-js/index.mdx
  site/src/components/ImportSrc.jsx
Labels: hacktoberfest-accepted

#870 full stop removed to maintain consistency
  site/src/content/projects/ssi/ssi.js
  site/src/content/projects/tbdex/tbdex.js
  site/src/content/projects/web5/web5.js
Labels: hacktoberfest-accepted

#792 Remove console statement and add retry logic for FeedbackWidget
  site/src/hooks/use-feedback-rating.js
  site/src/util/feedback-retry-wait.js
Labels: enhancement, hacktoberfest-accepted

#879 twitter name changed
  site/src/components/Community.jsx
  site/src/components/ConferenceCommunitySection.jsx
  site/src/pages/open-source/contributing.mdx
Labels: hacktoberfest-accepted

#892 cursor-pointer-added
  site/src/components/ApiDetails.jsx
Labels: hacktoberfest-accepted

#921 Fix broken DID Authentication link at `/site/docs/web5/build/apps/dinger-tutorial.mdx`
  site/docs/web5/build/apps/dinger-tutorial.mdx
Labels: hacktoberfest-accepted

#920 Fix the dead Protocols link on `/api/web5-js/dwn/protocol/` page
  site/api/web5-js/dwn/protocol.mdx
Labels: hacktoberfest-accepted

#928 Issue/926: Make TBD Monthly Spotlight clickable
  site/src/pages/community/index.js
Labels: hacktoberfest-accepted

#943 Accessibility for markdown files
  CODE_OF_CONDUCT.md
  README.md
Labels: hacktoberfest-accepted

#942 feat: create code snippets file for update dwn
  site/__tests__/web5/build/decentralized-web-nodes/update-dwn.test.js
  site/code-snippets/web5/build/decentralized-web-nodes/update-dwn.js
  site/src/util/code-snippets-map.json
Labels: hacktoberfest-accepted

#946 Updated updateDwnRecords with CodeSnippet
  site/code-snippets/web5/build/decentralized-web-nodes/update-dwn.js
  site/docs/web5/build/decentralized-web-nodes/update-to-dwn.mdx
Labels: hacktoberfest-accepted

#948 Fix typos and grammar
  site/blog/2023-10-11-dif-hackathon.md
  site/docs/ssi/create-schema.md
  site/docs/ssi/credential-issuance-service.md
  site/docs/ssi/credential-manifests.md
  site/docs/ssi/presentation-requests.md
  site/docs/ssi/ssi-console.md
  site/docs/tbdex/api-reference/tbdex-js/protocol/classes/Resource.md
  site/docs/tbdex/api-reference/tbdex-js/protocol/index.md
  site/docs/web5/learn/sync.md
  site/docs/web5/learn/verifiable-credentials.md
Labels: hacktoberfest-accepted
