Repository TBD54566975/developer.tbd.website, pull requests merged in 2024-10, with the labels that each got.

#1747 Fixes typos in the Open Standards at TBD Blog Post
  site/blog/2024-08-28-open-standards.md
Labels: hacktoberfest-accepted

#1745 Fix typo in tbDEX SDK content
  site/src/content/home/tbdex-cta.js
Labels: hacktoberfest-accepted, hacktoberfest, small

#1746 Fixes typos in API Reference Guides page and `self-sovereign` typos
  site-new/docs/glossary.md
  site/blog/2022-08-26-ssi-tbd-web5.md
  site/blog/2023-01-10-ssi-chat-gpt.md
  site/docs/api.mdx
  site/docs/glossary.md
  site/src/content/projects/tbdex/heading.mdx
Labels: hacktoberfest-accepted, hacktoberfest, small

#1751 Fix typos in Developer Website's Projects section on front page
  site/src/components/Project.jsx
  site/src/content/projects/project-index/projects.js
Labels: hacktoberfest-accepted, hacktoberfest, small

#1762 Fix Typos in 7 Unexpected Ways Verifiable Credentials Are Used Today Blog Post
  site/blog/2024-07-29-ways-we-use-vcs-today.md
Labels: hacktoberfest-accepted, hacktoberfest, small

#1763 Fix typo in issuer overview page
  site/docs/tbdex/issuer/overview.mdx
Labels: hacktoberfest-accepted, hacktoberfest, small

#1758 Fix Typos in Credential Issuance Page #1594
  site/docs/tbdex/issuer/vc-issuance.mdx
Labels: hacktoberfest-accepted, hacktoberfest, small

#1764 typo correction in Open Source Section on Front page
  site/src/content/open-source/heading.mdx
Labels: hacktoberfest-accepted, hacktoberfest, small

#1761 Fixes typo in Query DWN Records Page
  site/docs/web5/decentralized-web-nodes/query-from-dwn.mdx
Labels: hacktoberfest-accepted, hacktoberfest, small

#1768 Fix Typos in What Are DWNs Page
  site/docs/web5/decentralized-web-nodes/what-are-dwns.md
Labels: hacktoberfest-accepted, hacktoberfest, small

#1769 Updated docs
  site/docs/web5/verifiable-credentials/verify-vc.mdx
Labels: hacktoberfest-accepted, hacktoberfest, small

#1771 Fix Typos in Structuring a PFI App Page
  site/docs/tbdex/pfi/anatomy-of-a-pfi.mdx
Labels: hacktoberfest-accepted, hacktoberfest, small

#1775 Typo: Fix Typos in Top 8 TBD Hackathon Winners! Blog Post
  site/blog/2024-01-29-tbd-hackathon-winners.md
Labels: hacktoberfest-accepted, hacktoberfest, small

#1779 fix typo for shepherd
  site/blog/2024-04-08-did-dht.md
Labels: hacktoberfest-accepted, hacktoberfest, small

#1777 Update 2024-01-11-devcareer-winners.md
  site/blog/2024-01-11-devcareer-winners.md
Labels: hacktoberfest-accepted, hacktoberfest, small

#1781 fix: fix typos in web5 page
  site/src/content/projects/web5/web5.js
Labels: hacktoberfest-accepted, hacktoberfest, small

#1773 Typo: Fix Typos in What Are VCs Page
  site/docs/web5/verifiable-credentials/what-are-vcs.md
Labels: hacktoberfest-accepted, hacktoberfest, small

#1778 Change Word To Lowercase in VCs in DWNs Page
  site/docs/web5/verifiable-credentials/vcs-in-dwn.mdx
Labels: hacktoberfest-accepted, hacktoberfest, small

#1780 fix: fix typos in vc workflow page
  site/docs/web5/verifiable-credentials/fan-club-vc.mdx
Labels: hacktoberfest-accepted, hacktoberfest, small

#1776 Fix Typo in DID Document in Resolve a DID Page
  site/docs/web5/decentralized-identifiers/how-to-create-did.mdx
  site/docs/web5/decentralized-identifiers/how-to-resolve-a-did.mdx
Labels: hacktoberfest-accepted, hacktoberfest, small

#1789 #Add Blog About Key Management for DIDs
  site/src/externalContributors.json
  site/static/img/external-contributor/kiranbaliga.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1792 add blog for DWN
  site/src/externalContributors.json
  site/static/img/external-contributor/Ashit743_DWN_Web5.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1795 Create a new Blog About Web5
  pnpm-lock.yaml
  site/src/externalContributors.json
  site/static/img/external-contributor/chrissiku_the_future_0f_web.png
Labels: hacktoberfest-accepted, medium

#1794 #Add Blog Post About Verifiable Credentials (VCs)
  site/src/externalContributors.json
  site/static/img/external-contributor/Kiran_verificablecredentials_1.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1798 Create Your Own Blog About Resolving DIDs
  site/src/externalContributors.json
  site/static/img/external-contributor/how_to_resolve_dids.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1800 Create Your Own Blog Comparing Different DID Methods
  site/src/externalContributors.json
  site/static/img/external-contributor/Lymah123_comparing_DID_methods.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1805 Create Your Own YouTube Video About Web5
  site/src/externalContributors.json
  site/static/img/external-contributor/quick_start_web5_chrissiku.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1803 #Add blog about DRL
  site/src/externalContributors.json
  site/static/img/external-contributor/DRL.png
Labels: hacktoberfest-accepted, medium

#1808 Create Your Own Blog About Web5
  site/src/externalContributors.json
  site/static/img/external-contributor/Lymah123_understanding_web5_and_its_potential.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1812 Own Blog about Protocol Rules
  site/src/externalContributors.json
  site/static/img/external-contributor/ProtocolRules.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1814 Hacktoberfest Experience
  site/src/externalContributors.json
  site/static/img/external-contributor/hackexperience.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1816 #1813 Fixed the cards in the Community Spotlight Section
  site/src/pages/community/index.js
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1818 Create Your Own Blog About DWNs
  site/src/externalContributors.json
  site/static/img/external-contributor/Lymah123_understanding_dwns.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1830 Create Your Own Blog About DWNs
  site/src/externalContributors.json
  site/static/img/external-contributor/dwns_blog_chrissiku.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1835 Create Content on Web5 #1749
  site/src/externalContributors.json
  site/static/img/external-contributor/nabhel_web5.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1850 Create Your Own YouTube Short About Web5 #1737
  site/src/externalContributors.json
  site/static/img/external-contributor/web5short.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1854 Create Blog About My Experience in TBD Hacktoberfest
  site/src/externalContributors.json
  site/static/img/external-contributor/TBD_nabhel.png
  site/static/img/external-contributor/nabhel_web5.png
  site/static/img/external-contributor/web5_nabhel_new.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1853 Create Your Own Blog About Standing Up A PFI
  site/src/externalContributors.json
  site/static/img/external-contributor/Lymah123_PFI.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1859 Hacktoberfest 2024 Experience
  site/src/externalContributors.json
  site/static/img/external-contributor/hfest.png
Labels: hacktoberfest-accepted, hacktoberfest, medium

#1862 Create Your Own Blog About Your Experience in TBD Hacktoberfest - Submission 3
  site/src/externalContributors.json
  site/static/img/external-contributor/mohit_hacktoberfest_journey.png
Labels: hacktoberfest-accepted, hacktoberfest, medium
